#!/bin/bash
set -e

source setup_cb.cfg

# update CB_PROJECT on collector and restart services
if [ -n "${collector}" ];then
    ssh -i ~/.ssh/id_cb_collect cb-collect@${collector} \
        -o StrictHostKeyChecking=accept-new \
        sudo sed -ie \"s@CB_PROJECT=.*@CB_PROJECT=${source_repo}@\" \
        /etc/cloud_builder
    ssh -i ~/.ssh/id_cb_collect cb-collect@${collector} \
        -o StrictHostKeyChecking=accept-new \
        sudo systemctl restart cb-collect
fi

# initial setup of runners...
for runner in ${runners};do
    setup_runner "${runner}"
done
