#!/bin/bash
set -e

source setup_cb.cfg

runner_count=0
for runner in ${runners};do
    runner_count=$((runner_count + 1))
done

pushd /usr/local/kafka_2.12-2.2.1

# standard topics...
for topic in cb-response cb-info-request cb-info-response; do
    ./bin/kafka-topics.sh \
        --create \
        --zookeeper ${ZookeeperConnectString} \
        --replication-factor 2 \
        --partitions 10 \
        --topic ${topic}
done

# runner group topics...
for topic in ${runner_topics}; do
    ./bin/kafka-topics.sh \
        --create \
        --zookeeper ${ZookeeperConnectString} \
        --replication-factor 2 \
        --partitions 10 \
        --topic ${topic}
done

# retention times...
for topic in ${runner_topics}; do
    ./bin/kafka-topics.sh \
        --alter \
        --zookeeper ${ZookeeperConnectString} \
        --config retention.ms=3600000 \
        --topic ${topic}
done
for topic in cb-info-response cb-info-request; do
    ./bin/kafka-topics.sh \
        --alter \
        --zookeeper ${ZookeeperConnectString} \
        --config retention.ms=1800000 \
        --topic ${topic}
done

# update BootstrapServersString here
sudo sed -ie "s@  host:.*@  host: ${BootstrapServersString}@" \
    /etc/cloud_builder_broker.yml

# update this_host name here
sudo sed -ie "s@this_host:.*@this_host: ${control_plane}@" \
    /etc/cloud_builder_broker.yml

# update CB_PROJECT here
sudo sed -ie "s@CB_PROJECT=.*@CB_PROJECT=${source_repo}@" \
    /etc/cloud_builder

# setup runner count here for cb-ctl
echo "  runner_count: ${runner_count}" >> ~/.config/cb/cbctl.yml

# restart fetcher
sudo systemctl restart cb-fetch
