#!/bin/bash
set -e

source setup_cb.cfg

runner=$1

# update "BootstrapServersString" on runner
ssh -i ~/.ssh/id_cb_collect cb-collect@${runner} \
    -o StrictHostKeyChecking=accept-new \
    sudo sed -ie \"s@  host:.*@  host: ${BootstrapServersString}@\" \
    /etc/cloud_builder_broker.yml

# update "this_host" on runner
ssh -i ~/.ssh/id_cb_collect cb-collect@${runner} \
    -o StrictHostKeyChecking=accept-new \
    sudo sed -ie \"s@this_host:.*@this_host: ${runner}@\" \
    /etc/cloud_builder_broker.yml

# update CB_PROJECT on runner
ssh -i ~/.ssh/id_cb_collect cb-collect@${runner} \
    -o StrictHostKeyChecking=accept-new \
    sudo sed -ie \"s@CB_PROJECT=.*@CB_PROJECT=${source_repo}@\" \
    /etc/cloud_builder

# update CB_COLLECT_REPO_SERVER on runner
ssh -i ~/.ssh/id_cb_collect cb-collect@${runner} \
    -o StrictHostKeyChecking=accept-new \
    sudo sed -ie \"s@CB_COLLECT_REPO_SERVER=.*@CB_COLLECT_REPO_SERVER=${collector}@\" \
    /etc/cloud_builder

# restart services on runner
ssh -i ~/.ssh/id_cb_collect cb-collect@${runner} \
    -o StrictHostKeyChecking=accept-new \
    sudo systemctl restart cb-fetch-once cb-scheduler cb-info
