#!/bin/bash
set -e

source setup_cb.cfg

runner_count=0
for runner in ${runners};do
    runner_count=$((runner_count + 1))
done

# update BootstrapServersString/this_host on runners and collector
for runner in ${runners} ${collector};do
    ssh -i ~/.ssh/id_cb_collect cb-collect@${runner} \
        sudo sed -ie \"s@  host:.*@  host: ${BootstrapServersString}@\" \
        /etc/cloud_builder_broker.yml
    ssh -i ~/.ssh/id_cb_collect cb-collect@${runner} \
        sudo sed -ie \"s@this_host:.*@this_host: ${runner}@\" \
        /etc/cloud_builder_broker.yml
done

# update CB_RUNNERS/CB_PROJECT on runners and restart services
for runner in ${runners};do
    ssh -i ~/.ssh/id_cb_collect cb-collect@${runner} \
        sudo sed -ie \"s@CB_RUNNERS=.*@CB_RUNNERS=${runner_count}@\" \
        /etc/cloud_builder
    ssh -i ~/.ssh/id_cb_collect cb-collect@${runner} \
        sudo sed -ie \"s@CB_PROJECT=.*@CB_PROJECT=${source_repo}@\" \
        /etc/cloud_builder
    ssh -i ~/.ssh/id_cb_collect cb-collect@${runner} \
        sudo systemctl restart cb-fetch-once cb-scheduler cb-info
done

# update CB_RUNNERS/CB_PROJECT on collector and restart services
ssh -i ~/.ssh/id_cb_collect cb-collect@${collector} \
    sudo sed -ie \"s@CB_RUNNERS=.*@CB_RUNNERS=${runner_count}@\" \
    /etc/cloud_builder
ssh -i ~/.ssh/id_cb_collect cb-collect@${collector} \
    sudo sed -ie \"s@CB_PROJECT=.*@CB_PROJECT=${source_repo}@\" \
    /etc/cloud_builder
ssh -i ~/.ssh/id_cb_collect cb-collect@${collector} \
    sudo systemctl restart cb-collect
