#!/bin/bash
# Simple Cluster Layout consisting out of
# the control plane, a collector and two runners
# Very small instances (t2.micro) and max 10G of
# EBS storage. Low cost profile
#
set -e

# USER SETTINGS
# Name of ssh key pair which you have registered in EC2
key_name=ms

# AMI's
control_plane=ami-0da4193409e15953e
collector=ami-0b2748858e98ebabc
runner=ami-0a1c18525f9cf77b8

# Start Control Plane
aws ec2 run-instances \
    --count 1 \
    --image-id ${control_plane} \
    --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=cb-control-plane}]' \
    --instance-type t2.micro \
    --key-name ${key_name}

# Start Collector (RepoServer)
aws ec2 run-instances \
    --count 1 \
    --image-id ${collector} \
    --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=cb-collect}]' \
    --block-device-mapping "DeviceName=/dev/sda1,Ebs={VolumeSize=10}" \
    --instance-type t2.micro \
    --key-name ${key_name}

# Start 2 Runners
for name in cb-runner-1 cb-runner-2;do
    aws ec2 run-instances \
        --count 1 \
        --image-id ${runner} \
        --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$name}]" \
        --block-device-mapping "DeviceName=/dev/sda1,Ebs={VolumeSize=10}" \
        --instance-type t2.micro \
        --key-name ${key_name}
done
